version: '3'

tasks:
  default:
    cmds:
      - task: build
      - task: lint
      - task: test
  build:
    cmds:
      - go build
  lint:
    cmds:
      - go vet ./...
  test:
    cmds:
      - task: test:medium
      - task: test:large
  test:medium:
    cmds:
      - go test ./...
  test:large:
    preconditions:
      - test -f ./true
    cmds:
      - ./true