name: test true
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: setup task
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
      - run: task